### ISSUE TITLE
RocketChat Task List

### ISSUE THREAD

**Issue by hao-fang** [acl-org/emnlp-2020-virtual-conference#49]
This issue is used to track the main task list for RocketChat.

- [x] Sign a contract
  - [x] Get the estimated number of users from General Chair, Program Chairs, and Priscilla. ACL2020 had 5000 users.
  - [x] Get a trial account for `emnlp2020.rocket.chat` workspace (confirm with General Chair, Program Chairs, and Nitin about the workspace name). This can be your own personal email. You can also register a specific email (e.g., `emnlp2020rocketchat@gmail.com`) for this.
- [x] Check with General Chair, Program Chairs, and Priscilla to see whether they want to make the RocketChat history (or an anonymized version) public for research usage. ACL2020 didn't do this but apparently there were some interests in this. There are some privacy implications.
- [x] Configure OAuth2 (need to coordinate with @jcklie on this since it requires access to AWS). 
  * See the "AWS Cognito Setup" and "RocketChat OAuth Setup" sections in https://github.com/acl-org/acl-2020-virtual-conference/issues/53.
- [x] Create the "EMNLP2020 Admin Bot" account with full admin permissions. This bot can be used to create channels and make announcements.
  - [x] Change the profile photo to the ACL logo.
- [x] Create channels:  See #69 for the list of channels and their settings. ~See the [Channels](https://aclweb.org/adminwiki/index.php?title=2020Q3_Reports:_Virtual_Infrastructure_Chairs#Channels) subsection in our ACL2020 Report~. Most of these channels should be created with the "EMNLP2020 Admin Bot" account so this account has the ownership. Related issue: #20  **(Nov. 7)**
  - [x] Talk with workshop chairs to understand their needs, and see if each workshop can contribute a virtual infrastructure person to be in charge of the virtual infrastructure (e.g., creating RocketChat channels, updating website, etc.) You may need to coordinate with other folks to see whether they have started such conversations (cc @jcklie). The list of workshops (along with their short code name) can be found at https://docs.google.com/spreadsheets/d/1fru836Gf2T8ixYOmJaaXvbXZvEXX9kZ8Vi8NADopHTY/edit#gid=0
  - [x] Create general channels. ~These channels should be marked as "join by default".~ See #69 for details.
  - [x] Create channels for sponsors. You will need to first talk with the person who are in charge of the sponsor booths. @jcklie knows most of the sponsor booths for ACL2020. I don't know exactly our decisions for EMNLP2020.
  - [x] Create channels for each tutorials. This can be manually done by 1 volunteer. You probably need to reach out to tutorial chairs about this.
  - [x] Create channels for social events. You will need to talk with social organizers to see their needs.
  - [x] Create channels for papers (main conference, demo, CL, TACL, SRW), We asked one volunteer to use [this script](https://github.com/acl-org/acl-2020-virtual-conference-tools/blob/master/acl2020_tools/chat/make_poster_rooms.py) to automatically create these channels.
  - [x] Create channels for workshops using the same script. Coordinate with @jcklie to once the csv files are ready.
  - [x] ~Mark channels that should be listed first in the "Browse Channels" page. I don't remember what the config is. Once you have the trial workspace, I can take a look and update here. Basically, all non-paper channels are "promoted".~ *This is documented in #69 now -- see the column "Featured".)
- [x] Create a "On-Call Volunteer" account that is shared by on-call volunteers. This account should have enough permissions to moderate the RocketChat usage but not the full admin permission (see the next item).  **(Nov. 7)**
- [x] Configure permissions and roles. See #71. **(Nov. 7)**
  * ~You probably need to go through the whole list and make decisions. Feel free to ask me if you have questions. I'll also add some important ones below.~ 
  - [x] Turn off mention all and mention user permissions.
  - [x] Turn off the permission to view other user's email address (for privacy reason).
  - [x] Configure the permission for "On-Call Volunteer" account, and document it in #71.
- [x] Upload emoji. **(Nov. 7)**
  * In ACL2020, we asked one volunteer to put together a list of emoji and uploaded them to the workspace. See [this doc](https://docs.google.com/document/d/1wg8Ac_tf7kZULbhGU3t8gWkFj1D4ovBAs25e2D84n3o/edit?usp=sharing). 
  * You at least need the ACL logo.
  * We disallow normal users to upload emoji to avoid unexpected issues.
  * We didn't upload sponsor's logo to avoid potential legal issues.
- [x] Go through the "Administration Panel" to check the configurations. See details in #70. Both of the below sub-tasks are optional since they should be already covered by #70.
  - [x] Read https://github.com/acl-org/acl-2020-virtual-conference/issues/56 to understand some misc. issues. 
  - [x] Read [other considerations](https://aclweb.org/adminwiki/index.php?title=2020Q3_Reports:_Virtual_Infrastructure_Chairs#Other_considerations) subsection in our ACL2020 report.
- [x] ~Check whether there will be internal test scheduled before the conference. **(Nov. 3)**~
- [x] ~If you have internal test users before the conference, you may need to clear the channel history after the internal test period ends. **(Nov. 13)**~
  * ~We gave sponsors a test account for them to try RocketChat before the conference. You will need to disable these accounts and remove test messages & channels. I'm not sure what we are going to do for sponsors this year though.~
- [x] Make a plan for live QA for plenary sessions. **(Nov. 3)**. @jcklie can you do this?
  - [x] See the logistics described in #69. I (@hao-fang) explained this to the PCs and they are okay with the current plan. We didn't talk about Dory.app though.
  - [x] You will need to manage the #live and #keynote-xxx channels during the livestream time. You can either do it by yourself or find a volunteer for it. 
  - [x]  If you want to try [Dory.app](https://www.dory.app/), I can put you in touch with their co-founder to discuss scalability. See [other platforms](https://aclweb.org/adminwiki/index.php?title=2020Q3_Reports:_Virtual_Infrastructure_Chairs#Other_platforms) section in our ACL2020 report for some discussions.
- [x] Assign volunteers to handle the #organizer-registration-desk and #sponosr-registration-desk. See the descriptions in #69. **(Nov. 3)**
- [x] Assign a volunteer to handle #live and #keynote-xxx channels for the three plenary sessions. See the descriptions in #69.
- [x] Talk to Professional Conduct Committee to understand their need. **(Nov. 3)**
- [x] Volunteer training materials. See more in #50. **(Nov. 11)**
- [x] Understand that we will recommend people to set up their "Display Name" with pronouns & affiliation. See step 6 in this [login instruction doc](https://docs.google.com/document/d/1dGEUg5jNZwyK2w8RLhmgvz-DXq-Xu2_ezAveOYYZzY4/edit). I guess there is no action item for this, but it's useful to keep this in mind when people ask about it. **(Nov. 11)**
- [x] Send an email to all organizing committee (including tutorial & workshop organizers) to ask them to post a message in #organizer-registration-desk if they need to get the "owner" permission for their channels.
```
Hello EMNLP2020 organizers,

We will start to send out account information around this Thursday so you can access to the website & RocketChat. You can find descriptions of some RocketChat channels in the attached PDF.

Some of you may need to get the "Channel Owner" permission to perform certain actions in some channels, e.g., changing the topic & description of the channel, making a conference-wide announcement in the #announcements channel, etc. If you need to get such permission, please join the #organizer-registration-desk channel (https://emnlp2020.rocket.chat/channel/organizers-registration-desk) and post a message with the name of the channel. An on-call volunteer will help you from there.
Tutorial Chairs, Workshop Chairs, D&I Chairs -- Can you let tutorial/workshop/socials organizers know about this as well?

See you all in the Virtual EMNLP2020!
 ```
- [x] Before the conference starts, remind the RocketChat support team to scale up for upcoming traffics. (Just need to create a ticket in their support platform.) **(Nov. 13)**
- [x] Before the conference starts, clean up the channels & chat history. **(Nov. 15)**
  - [x] Remove test channels.
  - [x] Prune message histories for all public channels.
  - [x] Post a welcome message in #announcement using the Admin Bot account, and react with an :acl-logo emoji.
<img width="1220" alt="Screen Shot 2020-11-10 at 10 58 52 PM" src="https://user-images.githubusercontent.com/9957482/98779193-59066000-23a8-11eb-9095-a5a5f6ae1846.png">
