### ISSUE TITLE
Helpdesk Task List

### ISSUE THREAD

**Issue by hao-fang** [acl-org/emnlp-2020-virtual-conference#57]
- [x] Read the materials in https://github.com/acl-org/emnlp-2020-virtual-conference/issues/50.
- [x] Create a mailing list (e.g., `emnlp2020-virtual-helpdesk@googlegroups.com`)
- [x] Obtain an AWS access key for resetting user passwords and creating user accounts. (coordinate with @jcklie and @desilinguist). 
  * The script for resetting password is [here](https://github.com/acl-org/acl-2020-virtual-conference-tools/blob/master/acl2020_tools/awscognito/reset_user_password.sh). NOTE we hard-coded the password so it is easier to just email the password back to the user because sometimes they have trouble receiving the email auto-sent from AWS.
  * The script for creating a new user is [here](https://github.com/acl-org/acl-2020-virtual-conference-tools/blob/master/acl2020_tools/awscognito/create_new_user.sh). Check the first two entries in the [FAQ volunteers](https://docs.google.com/document/d/1mapDfq1HUGhu9kWn4HRVSS8evEme2d9M-3KQKQhzRZA/edit?usp=sharing) doc to get more context.
- [x] Obtain an On-Call Volunteer account. @jcklie needs to first create an account in AWS Cognito Pool, and @benotti need to give proper permissions in RocketChat for this account. Check the "RocketChat Tech Support Instructions" section in the [Training Materials](https://docs.google.com/document/d/1cTif1UiCPuv7DvJpSCxijTO_2QpG-JLGY_MDIJ1eIMQ/edit?usp=sharing) doc to get more context.
- [ ] Coordinate with the volunteer chair to manage on-call volunteers. 
- [x] Prepare a new doc for Training Materials.
  * It would be very useful to develop an escalation process.
  * Coordinate with other virtual infrastructure committee members to prepare the document. In particular, we use Gathertown for EMNLP2020, which is not in the ACL2020 so the training materials didn't cover this part.
- [x] add volunteers to googlegroups (needs to be done in advance because of some weird limit on how many emails can be added within 24 hours) (not required this time - we have a single mailbox for all helpdesk stuff)

- [x] Develop an escalation process (e.g. for people disrupting zoom calls)
