### ISSUE TITLE
Update sponsor booths

### ISSUE THREAD

**Issue by jcklie** [acl-org/emnlp-2020-virtual-conference#9]
- [x] Get feedback from sponsors whether changes to sponsor boothes are needed
- [x] Update information for every sponsor

**TODO:**

- [x] Add publications support (bytedance)
- [x] Add youtubes support (baidu)
- [x] Fix youtube links to use embedded one
- [x] Add gdrive
- [x] Add rocketchat
